config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :galleries
  resources :musics
  resources :tours
  resources :fans
  resources :news
  devise_for :users
  root 'welcome#index'

  get '/noticias' => 'welcome#noticias'
  get '/fanzone' => 'welcome#fanzone'
  get '/biografia' => 'welcome#biografia'
  get '/bonza_videos' => 'welcome#videos'
  get '/musica_video' => 'welcome#musica'
  get '/bonza_tour' => 'welcome#tour'
  get '/galeria' => 'welcome#galeria'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_path, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:user_id, :link, :disponible)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :disponible %>
    <%= form.check_box :disponible, id: :experience_disponible %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :video_link %>
  </div>

  <div class="actions">
    <%= form.submit class: "button button_primary"%>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div id="formario">

<h1>Editar Video</h1>

<%= render 'form', video: @video %>


</div>
</div>
</div>
</div>

app/views/videos/index.html.erb
<%= render 'welcome/bread' %>

<div class="container">

<%= link_to "Nuevo Video", new_video_path, class: "button button_primary" %>

<div id="formario">

<h1>Videos</h1>
<br>
<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>disponible</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.disponible %></td>
        <td><%= video.link %></td>
        <td><%= link_to 'Ver más', video %></td>
        <td><%= link_to 'Editar', edit_video_path(video) %></td>
        <td><%= link_to 'Eliminar', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

</div>
</div>

app/views/videos/new.html.erb
<%= render 'welcome/bread' %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div id="formario">

<h1>Nuevo Video</h1>

<%= render 'form', video: @video %>

</div>
</div>
</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @video.user %>
</p>

<p>
  <strong>Link:</strong>
  <%= @video.link %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>