config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :galleries
  resources :musics
  resources :tours
  resources :fans
  resources :news
  devise_for :users
  root 'welcome#index'

  get '/noticias' => 'welcome#noticias'
  get '/fanzone' => 'welcome#fanzone'
  get '/biografia' => 'welcome#biografia'
  get '/bonza_videos' => 'welcome#videos'
  get '/musica_video' => 'welcome#musica'
  get '/bonza_tour' => 'welcome#tour'
  get '/galeria' => 'welcome#galeria'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name, 					:validate => false
	attribute :email, 				:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :phone,     		:validate => false
	attribute :donde, 		   	:validate => false
	attribute :comments, 			:validate => false
	attribute :nickname, 			:captcha => true

def headers 
	{
	:subject => "Nueva Confirmación",
	:to => "bonza@mikebonza.com",
	:cc => "alejandroromo14@gmail.com",
	:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/fan.rb
class Fan < ApplicationRecord
  belongs_to :user

mount_uploader :foto4, Foto4Uploader
mount_uploader :foto5, Foto5Uploader
mount_uploader :foto6, Foto6Uploader
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
 mount_uploader :photo10, Foto10Uploader
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user

mount_uploader :foto1, Foto1Uploader
mount_uploader :foto2, Foto2Uploader
mount_uploader :foto3, Foto3Uploader

end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user

mount_uploader :foto7, Foto7Uploader
mount_uploader :foto8, Foto8Uploader
mount_uploader :foto9, Foto9Uploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :galleries
  has_many :musics
  has_many :tours
  has_many :news
  has_many :fans
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /fans
  # GET /fans.json
  def index
    @fans = Fan.all
  end

  # GET /fans/1
  # GET /fans/1.json
  def show
  end

  # GET /fans/new
  def new
    @fan = Fan.new
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.json
  def create
    @fan = Fan.new(fan_params)
    @fan.user_id = current_user.id

    respond_to do |format|
      if @fan.save
        format.html { redirect_to fans_path, notice: 'Fan was successfully created.' }
        format.json { render :show, status: :created, location: @fan }
      else
        format.html { render :new }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fans/1
  # PATCH/PUT /fans/1.json
  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to fans_path, notice: 'Fan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan }
      else
        format.html { render :edit }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fans/1
  # DELETE /fans/1.json
  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url, notice: 'Fan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan
      @fan = Fan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_params
      params.require(:fan).permit(:user_id, :title, :content, :link, :foto4, :foto5, :foto6, :disponible)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    @news.user_id = current_user.id

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_path, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_path, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:user_id, :title, :content, :link, :foto1, :foto2, :foto3, :disponible, :fecha)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @tours = Tour.all.order('id DESC').limit(3)
  end

  def noticias
  	@news = News.all.order('fecha DESC').where(:disponible => true)
  end

  def fanzone
  	@fans = Fan.all.order('id DESC')
  end

  def biografia
  	
  end

  def videos
  	@videos = Video.all.order('id DESC')
  end

  def musica
  	@musics = Music.all.order('id DESC').where(:disponible => true)
    @videos = Video.all.order('id DESC').where(:disponible => true)
  end

  def tour
  	@tours = Tour.all.order('fecha_inicio DESC').where(:disponible => true)
  end


  def galeria
    @galleries = Gallery.all.order('id DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_bread.html.erb
<section>
	<nav>
		<ol class="cd-breadcrumb custom-separator">
			<li class="<%= 'current' if current_page?(news_index_path) %>"><a href="<%= news_index_path %>">Noticias</a></li>

			<li class="<%= 'current' if current_page?(tours_path) %>"><a href="<%= tours_path %>">Tours</a></li>

			<li class="<%= 'current' if current_page?(videos_path) %>"><a href="<%= videos_path %>">Videos</a></li>

			<li class="<%= 'current' if current_page?(musics_path) %>"><a href="<%= musics_path %>">Musica</a></li>

		</ol>
	</nav>
</section> <br><br>

app/views/welcome/biografia.html.erb
<div class="bios">
	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white"></h1>
				<h2 class="title white">Este es Mike Bonza</h2>
			</div>
	</div>
	</div>
</div>
<div id="pinta">
</div>


<div id="ribu">
<div class="row">
	<div class="col-md-6">
		<div class="corte">
		<%= image_tag "cover.png" %>
		</div>
	</div>

	<div class="container">
	<div class="col-md-6">
		<div id="tara">
			<h1 class="big_title">Biografía</h1>
			<hr class="left">
<h4 class="shadow">C</h4>
		<p>
	
	Cantante Mexicano, nacido en la Ciudad de México, se enamoró de la música escuchando desde
pequeño, a leyendas como Frank Sinatra, Dean Martin, Sammy Davis Jr. y Elvis Presley. Es por esto
por lo que inicia su carrera artística con un disco y un show alucinante en el cual canta temas de
estos grandes artistas. <br><br><br>
En palabras de Mike, su corazón vibra con lo siguiente: “Mi ideal es ser un showman total; lograr
llevar al mayor número de personas mi música, mi energía y mi pasión”. <br><br><br>
Mike cree totalmente que la música es un vehículo para mejorar al mundo, unir a las personas, y a
los países. Por esto uno de sus objetivos es posicionarse a nivel internacional; llegar al mayor
número de personas y poder hacer colaboraciones con diferentes artistas de todo el mundo:
creando puntos de encuentro a través de la música.

		</p>

		<a class= "button button_secondary" href="<%= new_contact_path %>">Contrataciones</a>
		<br><br>
		<%= image_tag "concierto.png" %>
	</div>
	</div>
	</div>
</div>
</div>

app/views/welcome/galeria.html.erb
<div class="container">
    <div id="insta">

        <h1>Galería</h1>
        <hr>
        <h4 class="shadow">L</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit accusamus id repellat deserunt qui dignissimos sunt minus consequatur, voluptate, quisquam repudiandae ducimus laboriosam debitis! Nihil consequatur quibusdam voluptatem autem officiis!</p> <br><br><br>

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-1b74fc62-66f2-4b03-8f92-0025e7e7336c"></div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="heros visible-xs">

	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white">El Crooner</h1>
				<h2 class="title white"> de esta generación</h2>
			</div>
	</div>
	</div>
</div>


<div class="hero hidden-xs">

<video playsinline autoplay muted loop poster="cover2.png" id="bgvideo" width="x" height="y">
<source src="images/video_home.mp4" type="video/mp4">
</video>

	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white">El Crooner</h1>
				<h2 class="title white"> de esta generación</h2>
			</div>
	</div>
	</div>
</div>

<div id="pinta">
</div>

		<div id="contact">
			<div class="container">
				<div class="row">
					<div class="col-md-6">
				<h1 class="white title">ZONA FAN</h1>
				<h6 class="white subtitle">Suscríbete para tener noticias exclusivas</h6>
				</div>

					<div id="foca2">
						<%= form_for @contact do |f| %>
						<div class="col-md-2">
							<br><br>
								<%= f.text_field :email, required:true, placeholder: "Email" %>

								<%= f.text_field :donde, :value => "#{params[:controller]} - #{request.original_url}", class: "hidden" %>
									<%= f.text_field :nickname, hint: 'Esto se queda en blanco', class: "hidden" %>
						</div>

						<div class="col-md-2">
							<br><br>
							<%= f.text_field :phone, placeholder: "Teléfono" %>
						</div>
									
						<div class="col-md-2">
							<br><br>
							<%= f.submit "Suscríbeme", class:"buttona button_secondary"%>
						</div>			
						<% end %>
					

					</div>
			</div>
		</div>
	</div>

<div id="section" class="black">
	<div class="container">
			<h1 class="big_title">Mike Bonza Tour</h1>
			<hr class="left">

	<% @tours.each_with_index do |tour, i| %>
<div class="row">
<div class="col-md-8">
<div id="touri">
	<h3 class="bold"><%=tour.fecha %></h3> <br>
	<h3><%=tour.lugar %></h3>
	<%= link_to "Más información", tour.link, class: "button button_white" %>
</div>
</div>
</div>
	<% end %> <br><br>
  <%= link_to "TODO EL TOUR DE MIKE BONZA", bonza_tour_path, class: "butra_white" %>  
	</div>
</div>



<div id="section" class="">
	<div class="container">
		<div class="row">
			<h1 class="big_title_der">Galería</h1>
			<hr class="right">

    <div id="insta">

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-1b74fc62-66f2-4b03-8f92-0025e7e7336c"></div>
    </div>

  <%= link_to "Sígueme en Instagram", "https://www.instagram.com/themikebonza", class: "butra" %>  

		</div>
	</div>
</div>

app/views/welcome/musica.html.erb
<div class="musi">
	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white">Mkie Bonza</h1>
				<h2 class="title white">Música & Video</h2>
			</div>
	</div>
	</div>
</div>
<div id="pinta">
</div>


<div id="section" class="">
	<div class="container">
		<div class="row">
			<h1 class="big_title">Música</h1>
			<hr class="left">

			<% @musics.each_with_index do |music, i| %>
				<div class="col-md-4 col-sm-6">
			<div id="cancion">
				<%= simple_format(music.link, {}, sanitize: false) %>
			</div>
				</div>
			<% end %>
 

		</div>
	</div>
</div>


<div id="section" class="gris">
	<div class="container">
		<div class="row">
			<h1 class="big_title_der">Video</h1>
			<hr class="right">

			<% @videos.each_with_index do |video, i| %>
				<div class="col-md-6 col-sm-6">
			<div id="cancion">
				<%= simple_format(video.link, {}, sanitize: false) %>
			</div>
				</div>
			<% end %> 

		</div>
	</div>
</div>

app/views/welcome/noticias.html.erb
<div class="newsi">
	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white">Entérate Antes</h1>
				<h2 class="title white">Lo mejor de Mike Bonza</h2>
			</div>
	</div>
	</div>
</div>
<div id="pinta">
</div>


<div id="section">
	<div class="container">
			<h1 class="big_title">Noticias</h1>
			<hr class="left">

		
			<% @news.each_with_index do |news, i| %>
				<div class="col-md-4">
			<div id="noticia">
				<div class="image">
					<%= image_tag news.foto1 %>
				</div>
				<h2><%=news.title %></h2>
				<h4><%=news.try(:fecha) %></h4>
				<br>
				<p><%= news.content.truncate(150)%></p> <br><br>

				<%= link_to "Seguir Leyendo", "#", data: {toggle: "modal", target: "#modal#{i}"}, class: "butra" %>
			</div>

			<div id="modli">
				<!-- Modal -->
				<div class="modal fade" id="modal<%=i%>" role="dialog">
					<div class="modal-dialog modal-md">
						<div class="modal-content">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
							</div>
							<div class="modal-body">
								<h1 class="big_title"><%= news.title %></h1>
								<hr class="left">
								<p><%=news.created_at.to_date %></p>

								<br>
								<div id="boby">
									<!-- body -->
									<h4 class="shadow"><%=news.content.first %></h4>
									<p><%= simple_format news.content %></p>
									<br>
									<a class= "button button_secondary" href="<%= news.link %>">Más información</a>
									<br>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--  -->
				</div>
			<% end %>
	</div>
</div>


<script>
    $(".owl-carousel").owlCarousel(
  {
    items:1,
    autoHeight:true,
  });
</script>

app/views/welcome/tour.html.erb
<div class="town">
	<div class="container">
	<div class="row">
			<div id="banner_1">
				<h1 class="subtitle white">Mkie Bonza</h1>
				<h2 class="title white">Tour</h2>
			</div>
	</div>
	</div>
</div>
<div id="pinta">
</div>


<div id="section" class="black">
	<div class="container">
			<h1 class="big_title">Mike Bonza Tour</h1>
			<hr class="left">

	<% @tours.each_with_index do |tour, i| %>
<div class="row">
<div class="col-md-8">
<div id="touri">
	<h3 class="bold"><%=tour.fecha %></h3> <br>
	<h3><%=tour.lugar %></h3>
	<%= link_to "Más información", tour.link, class: "button button_white" %>
</div>
</div>
</div>
	<% end %> 
	</div>
</div>

app/views/welcome/videos.html.erb
<div id="section">
	<div class="container">
		<h1>Videos</h1>
		<h4 class="shadow">L</h4>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptates iusto est earum nostrum animi minima, sapiente provident temporibus consequatur dignissimos dolores assumenda, quas veritatis magni doloremque laboriosam corporis id!</p>
		<hr>

		
			<% @videos.each_with_index do |video, i| %>
				<div class="col-md-6 col-sm-6">
			<div id="cancion">
				<%= simple_format(video.link, {}, sanitize: false) %>
			</div>
				</div>
			<% end %>
	</div>
</div>