config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :galleries
  resources :musics
  resources :tours
  resources :fans
  resources :news
  devise_for :users
  root 'welcome#index'

  get '/noticias' => 'welcome#noticias'
  get '/fanzone' => 'welcome#fanzone'
  get '/biografia' => 'welcome#biografia'
  get '/bonza_videos' => 'welcome#videos'
  get '/musica_video' => 'welcome#musica'
  get '/bonza_tour' => 'welcome#tour'
  get '/galeria' => 'welcome#galeria'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
  end

  # GET /musics/new
  def new
    @music = Music.new
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id

    respond_to do |format|
      if @music.save
        format.html { redirect_to musics_path, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to musics_path, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:user_id, :link , :disponible)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= form_with(model: music, local: true) do |form| %>
  <% if music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :disponible %>
    <%= form.check_box :disponible, id: :experience_disponible %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :music_link %>
  </div>

  <div class="actions">
    <%= form.submit class: "button button_primary" %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div id="formario">

<h1>Editar Canción</h1>

<%= render 'form', music: @music %>


</div>
</div>
</div>
</div>

app/views/musics/index.html.erb
<%= render 'welcome/bread' %>

<div class="container">

<%= link_to "Nueva Canción", new_music_path, class: "button button_primary" %>

<div id="formario">

<h1>Música</h1>

<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>disponible</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.disponible %></td>
        <td><%= music.link %></td>
        <td><%= link_to 'Ver más', music %></td>
        <td><%= link_to 'Editar', edit_music_path(music) %></td>
        <td><%= link_to 'Eliminar', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

</div>
</div>

app/views/musics/new.html.erb
<%= render 'welcome/bread' %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<div id="formario">

<h1>Nueva Canción</h1>

<%= render 'form', music: @music %>


</div>
</div>
</div>
</div>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @music.user %>
</p>

<p>
  <strong>Link:</strong>
  <%= @music.link %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>