config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resources :galleries
  resources :musics
  resources :tours
  resources :fans
  resources :news
  devise_for :users
  root 'welcome#index'

  get '/noticias' => 'welcome#noticias'
  get '/fanzone' => 'welcome#fanzone'
  get '/biografia' => 'welcome#biografia'
  get '/bonza_videos' => 'welcome#videos'
  get '/musica_video' => 'welcome#musica'
  get '/bonza_tour' => 'welcome#tour'
  get '/galeria' => 'welcome#galeria'

  resources :contacts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name, 					:validate => false
	attribute :email, 				:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :phone,     		:validate => false
	attribute :donde, 		   	:validate => false
	attribute :comments, 			:validate => false
	attribute :nickname, 			:captcha => true

def headers 
	{
	:subject => "Nueva Confirmación",
	:to => "bonza@mikebonza.com",
	:cc => "alejandroromo14@gmail.com",
	:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/fan.rb
class Fan < ApplicationRecord
  belongs_to :user

mount_uploader :foto4, Foto4Uploader
mount_uploader :foto5, Foto5Uploader
mount_uploader :foto6, Foto6Uploader
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :user
 mount_uploader :photo10, Foto10Uploader
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user

mount_uploader :foto1, Foto1Uploader
mount_uploader :foto2, Foto2Uploader
mount_uploader :foto3, Foto3Uploader

end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user

mount_uploader :foto7, Foto7Uploader
mount_uploader :foto8, Foto8Uploader
mount_uploader :foto9, Foto9Uploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :galleries
  has_many :musics
  has_many :tours
  has_many :news
  has_many :fans
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /fans
  # GET /fans.json
  def index
    @fans = Fan.all
  end

  # GET /fans/1
  # GET /fans/1.json
  def show
  end

  # GET /fans/new
  def new
    @fan = Fan.new
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.json
  def create
    @fan = Fan.new(fan_params)
    @fan.user_id = current_user.id

    respond_to do |format|
      if @fan.save
        format.html { redirect_to fans_path, notice: 'Fan was successfully created.' }
        format.json { render :show, status: :created, location: @fan }
      else
        format.html { render :new }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fans/1
  # PATCH/PUT /fans/1.json
  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to fans_path, notice: 'Fan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan }
      else
        format.html { render :edit }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fans/1
  # DELETE /fans/1.json
  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url, notice: 'Fan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan
      @fan = Fan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_params
      params.require(:fan).permit(:user_id, :title, :content, :link, :foto4, :foto5, :foto6, :disponible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= csrf_meta_tags %>
	<%= display_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<script defer src="https://use.fontawesome.com/releases/v5.1.1/js/all.js" integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a" crossorigin="anonymous"></script>
	  <%= display_meta_tags site: 'Mike Bonza' %>
</head>


<body>
	<% if alert %>
	<p class="alert"><%= alert %></p>
	<% elsif notice %>
	<p class="notice"><%= notice %></p>
	<% end %>



	<div id="navin">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to root_path do %>
					<%= image_tag "mike_bonza_logo.svg" %>
					<% end %>
				</div>


				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li class="<%= 'activo' if current_page?(bonza_tour_path) %>"><a href="<%=bonza_tour_path %>">Tour</a></li>
						<li class="<%= 'activo' if current_page?(musica_video_path) %>"><a href="<%=musica_video_path %>">Música & Video</a></li>
						<li class="<%= 'activo' if current_page?(noticias_path) %>"><a href="<%=noticias_path %>">Noticias</a></li>
						<li class="<%= 'activo' if current_page?(biografia_path) %>"><a href="<%=biografia_path %>">Biografía</a></li>
						<li class="<%= 'activo' if current_page?(new_contact_path) %>"><a href="<%=new_contact_path %>">Contacto</a></li>

						<% if user_signed_in? %>
						<li>
							<%= link_to 'Dashboard', news_index_path %>
						</li>
						<% end %>
						<% if user_signed_in? %>
						<li class="mini"> <a href="<%= destroy_user_session_path %>" data-method='delete'>
							Cerrar Sesión
						</a></li>
						<% else %>
						<li class="mini"><a href="<%= new_user_session_path %>"> Iniciar Sesión </a></li>
						<% end %>

					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>
	</div>


	<div id="idiom">
		<div class="container">
		<ul>
			<li>
				<%= link_to "http://www.en.mikebonza.com" do %>
				<h3>EN</h3>
				<% end %>
			</li>
			<li>
				<%= link_to "http://www.mikebonza.com" do %>
				<h3 class="ac">ES</h3>
				<% end %>
			</li>
			<li>
				<h3><span class="fas fa-globe-americas"></span></h3>
			</li>
		</ul>
		</div>
	</div>
	
	<!-- your content here -->
	<div id="content">
		<%= yield %>
	</div>

	
		<div id="contact">
			<div class="container">
				<div class="row">
				<h1 class="white title">CONOCE MÁS DE MÍ</h1>
				<h2 class="white subtitle">MÁS INFORMACIÓN, CONTRATACIONES, PREGUNTAS...</h2>

				<%= link_to "Contáctame", new_contact_path, class: "button button_secondary" %>
			</div>
		</div>
	</div>



	<div id="footers">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<ul>
						<li>
							<%= link_to "https://www.instagram.com/themikebonza", :target => "_blank" do %>
							<span class="fab fa-instagram"></span>
							<% end %>
						</li>

						<li>
							<%= link_to "https://www.facebook.com/BonzaMike", :target => "_blank" do %>
							<span class="fab fa-facebook"></span>
							<% end %>
						</li>

						<li>
							<%= link_to "https://twitter.com/bonza_mike", :target => "_blank" do %>
							<span class="fab fa-twitter"></span>
							<% end %>
						</li>

						<li>
							<%= link_to "https://www.youtube.com/channel/UCNUQ3Q8NTFS1V7osWrS-p0w", :target => "_blank" do %>
							<span class="fab fa-youtube"></span>
							<% end %>
						</li>

						<li>
							<%= link_to "https://open.spotify.com/artist/7wts4mA8U3sZ23Sf4XSlaX", :target => "_blank" do %>
							<span class="fab fa-spotify"></span>
							<% end %>
						</li>

						<li>
							<%= link_to "https://itunes.apple.com/mx/artist/mike-bonza/1417471439?l=en", :target => "_blank" do %>
							<span class="fab fa-apple"></span>
							<% end %>
						</li>
					</ul> <br><br>
				</div>

				<div class="col-md-4 col-md-offset-2">
					<h3 class="white bold">SUSCRÍBETE PARA ENTERARTE <br>
					DE MIKE BONZA ANTES QUE NADIE</h3> <br>
					<div id="foca">
						<%= form_for @contact do |f| %>
								<%= f.text_field :email, required:true %><%= f.submit "Suscríbeme", class:"buttona button_terciary"%>

								<%= f.text_field :donde, :value => "#{params[:controller]} - #{request.original_url}", class: "hidden" %>
									<%= f.text_field :nickname, hint: 'Esto se queda en blanco', class: "hidden" %>
									
						<% end %>
					</div>

					</div>
				</div>
			</div>
		</div>

	<div id="copy">
		<p class="center">Copyright © 2018. All Rights Reserved.</p>
	</div>


</body>
</html>